### ISSUE TITLE
Errors during SSR

### ISSUE THREAD

**Issue by igoradamenko** [orbita-center/react-dadata-box#67]
Hey! 

We're using this component in a project that we render on a server.

But there is a line which triggers an error:

https://github.com/orbita-center/react-dadata-box/blob/39a98fa6950c48c7d84fbae5d15cfbb30711bb6c/src/index.js#L223

Is it possible to move it into `componentDidMount`? It looks like it's not used for the first render.

We would like to do it, but not sure about the status of this component. Is it still maintained?

**Comment by RUVATA** [comment]
If you have a mind about how to fix your case - make PR. 
I can publish the **hotfix** release with it

**Comment by RUVATA** [comment]
@igoradamenko 
Your transfer proposal (initialization of XMLHttpRequest to componentDidMount) will be implemented as part of #64 
that's coming soon

**Comment by igoradamenko** [comment]
@RUVATA, oh, thanks! I was trying to find time to implement this, but (as usually) failed 😞

**Comment by RUVATA** [comment]
@igoradamenko 
implementation it turned out to be simple
and literally like you suggested.

see: [src/index.js:227](https://github.com/RUVATA/react-dadata-box/commit/2bf5c35b8e3ecffc93f10cee1259bb3378963d55#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556R227) on this commit 2bf5c35b8e3ecffc93f10cee1259bb3378963d55

for base logic of component this change - doesn't change anything. 
If it is solve problem with SSR - this is almost free

**Comment by igoradamenko** [comment]
@RUVATA, it definitely solves the problem, thanks!

**Comment by RUVATA** [comment]
@igoradamenko 
at now published [1.3.7 version](https://www.npmjs.com/package/react-dadata-box/v/1.3.7) of react-data-box lib

I invite you to update the version of the package - and post feedback about it solves your problem or give your requested functionality

**Comment by igoradamenko** [comment]
Hey @RUVATA.

We've updated to the latest version and everything works perfectly 👌 

Thanks again 🐨
